#pragma once
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: /home/basson/Develop/Main/lic/converter/HellenicaRus16px.xml
* name: HellenicaRus16px
* family: Hellenica
* size: 23
* style: Regular
* included characters:  !#0123456789°.,
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
*
* preset name: Monochrome_Font
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Threshold Dither 255
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     uint8_t dataLenght;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#include "../lib/qymui/types.hpp"



#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x20[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const qymui::tImage HellenicaRus16px_0x20 = { image_data_HellenicaRus16px_0x20,
    7, 16, 8, 14};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x21[22] = {
    // ∙█████████∙
    // ∙█████████∙
    // ∙█████████∙
    // ∙∙∙∙███∙∙∙∙
    // ∙∙∙∙███∙∙∙∙
    // ∙∙∙∙███∙∙∙∙
    // ∙∙∙∙███∙∙∙∙
    // ∙∙∙∙███∙∙∙∙
    // ∙∙∙∙███∙∙∙∙
    // ∙∙∙∙███∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙███∙∙∙∙
    // ∙∙∙∙███∙∙∙∙
    // ∙∙∙∙███∙∙∙∙
    0x7f, 0xcf, 0xf9, 0xff, 0x07, 0x00, 0xe0, 0x1c, 0x03, 0x80, 0x70, 0x0e, 0x01, 0xc0, 0x00, 0x00, 0x00, 0x00, 0x1c, 0x03, 0x80, 0x70
};
static const qymui::tImage HellenicaRus16px_0x21 = { image_data_HellenicaRus16px_0x21,
    11, 16, 8, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x23[34] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙███∙∙███∙∙∙∙
    // ∙∙∙∙∙███∙∙███∙∙∙∙
    // ∙∙██████████████∙
    // ∙∙██████████████∙
    // ∙∙██████████████∙
    // ∙∙∙∙∙███∙∙███∙∙∙∙
    // ∙∙∙∙∙███∙∙███∙∙∙∙
    // ∙∙∙∙∙███∙∙███∙∙∙∙
    // ∙∙██████████████∙
    // ∙∙██████████████∙
    // ∙∙██████████████∙
    // ∙∙∙∙∙███∙∙███∙∙∙∙
    // ∙∙∙∙∙███∙∙███∙∙∙∙
    // ∙∙∙∙∙███∙∙███∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x03, 0x9c, 0x01, 0xce, 0x07, 0xff, 0xe3, 0xff, 0xf1, 0xff, 0xf8, 0x1c, 0xe0, 0x0e, 0x70, 0x07, 0x38, 0x1f, 0xff, 0x8f, 0xff, 0xc7, 0xff, 0xe0, 0x73, 0x80, 0x39, 0xc0, 0x1c, 0xe0, 0x00, 0x00
};
static const qymui::tImage HellenicaRus16px_0x23 = { image_data_HellenicaRus16px_0x23,
    17, 16, 8, 34};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x2c[12] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙███∙∙
    // ∙███∙∙
    // ∙███∙∙
    // ∙∙██∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x71, 0xc7, 0x0c
};
static const qymui::tImage HellenicaRus16px_0x2c = { image_data_HellenicaRus16px_0x2c,
    6, 16, 8, 12};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x2e[12] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙███∙∙
    // ∙███∙∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x71, 0xc7, 0x00
};
static const qymui::tImage HellenicaRus16px_0x2e = { image_data_HellenicaRus16px_0x2e,
    6, 16, 8, 12};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x30[38] = {
    // ∙∙∙∙∙█████████∙∙∙∙∙
    // ∙∙∙∙███████████∙∙∙∙
    // ∙∙∙████∙∙∙∙∙████∙∙∙
    // ∙∙████∙∙∙∙∙∙∙████∙∙
    // ∙∙███∙∙∙∙∙∙∙∙∙███∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙███∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙███∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙███∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙███∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙███∙
    // ∙∙███∙∙∙∙∙∙∙∙∙███∙∙
    // ∙∙████∙∙∙∙∙∙∙████∙∙
    // ∙∙∙████∙∙∙∙∙████∙∙∙
    // ∙∙∙∙███████████∙∙∙∙
    // ∙∙∙∙∙█████████∙∙∙∙∙
    // ∙∙∙∙∙∙∙█████∙∙∙∙∙∙∙
    0x07, 0xfc, 0x01, 0xff, 0xc0, 0x78, 0x3c, 0x1e, 0x03, 0xc3, 0x80, 0x38, 0xe0, 0x03, 0x9c, 0x00, 0x73, 0x80, 0x0e, 0x70, 0x01, 0xce, 0x00, 0x38, 0xe0, 0x0e, 0x1e, 0x03, 0xc1, 0xe0, 0xf0, 0x1f, 0xfc, 0x01, 0xff, 0x00, 0x0f, 0x80
};
static const qymui::tImage HellenicaRus16px_0x30 = { image_data_HellenicaRus16px_0x30,
    19, 16, 8, 38};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x31[38] = {
    // ∙∙█████████∙∙∙∙∙∙∙∙
    // ∙∙█████████∙∙∙∙∙∙∙∙
    // ∙∙█████████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙
    // ∙∙███████████████∙∙
    // ∙∙███████████████∙∙
    // ∙∙███████████████∙∙
    0x3f, 0xe0, 0x07, 0xfc, 0x00, 0xff, 0x80, 0x00, 0x70, 0x00, 0x0e, 0x00, 0x01, 0xc0, 0x00, 0x38, 0x00, 0x07, 0x00, 0x00, 0xe0, 0x00, 0x1c, 0x00, 0x03, 0x80, 0x00, 0x70, 0x00, 0x0e, 0x00, 0x7f, 0xff, 0x0f, 0xff, 0xe1, 0xff, 0xfc
};
static const qymui::tImage HellenicaRus16px_0x31 = { image_data_HellenicaRus16px_0x31,
    19, 16, 8, 38};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x32[38] = {
    // ∙∙█████████████∙∙∙∙
    // ∙∙██████████████∙∙∙
    // ∙∙███████████████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙∙∙∙█████████████∙∙
    // ∙∙██████████████∙∙∙
    // ∙∙█████████████∙∙∙∙
    // ∙████∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙███████████████∙∙∙
    // ∙███████████████∙∙∙
    // ∙███████████████∙∙∙
    0x3f, 0xfe, 0x07, 0xff, 0xe0, 0xff, 0xfe, 0x00, 0x01, 0xc0, 0x00, 0x38, 0x00, 0x07, 0x03, 0xff, 0xe1, 0xff, 0xf8, 0x3f, 0xfe, 0x0f, 0x00, 0x01, 0xc0, 0x00, 0x38, 0x00, 0x07, 0x00, 0x00, 0xff, 0xfe, 0x1f, 0xff, 0xc3, 0xff, 0xf8
};
static const qymui::tImage HellenicaRus16px_0x32 = { image_data_HellenicaRus16px_0x32,
    19, 16, 8, 38};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x33[36] = {
    // ∙∙███████████████∙
    // ∙∙███████████████∙
    // ∙∙███████████████∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙
    // ∙∙∙██████████████∙
    // ∙∙∙██████████████∙
    // ∙∙∙██████████████∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙
    // ∙∙███████████████∙
    // ∙∙███████████████∙
    // ∙∙███████████████∙
    0x3f, 0xff, 0x8f, 0xff, 0xe3, 0xff, 0xf8, 0x00, 0x0e, 0x00, 0x03, 0x80, 0x00, 0xe1, 0xff, 0xf8, 0x7f, 0xfe, 0x1f, 0xff, 0x80, 0x00, 0xe0, 0x00, 0x38, 0x00, 0x0e, 0x00, 0x03, 0x8f, 0xff, 0xe3, 0xff, 0xf8, 0xff, 0xfe
};
static const qymui::tImage HellenicaRus16px_0x33 = { image_data_HellenicaRus16px_0x33,
    18, 16, 8, 36};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x34[38] = {
    // ∙∙∙███∙∙∙∙∙∙███∙∙∙∙
    // ∙∙∙███∙∙∙∙∙∙███∙∙∙∙
    // ∙∙∙███∙∙∙∙∙∙███∙∙∙∙
    // ∙∙∙███∙∙∙∙∙∙███∙∙∙∙
    // ∙∙████∙∙∙∙∙∙███∙∙∙∙
    // ∙∙███∙∙∙∙∙∙∙███∙∙∙∙
    // ∙∙███∙∙∙∙∙∙∙███∙∙∙∙
    // ∙∙███∙∙∙∙∙∙∙███∙∙∙∙
    // ∙████∙∙∙∙∙∙∙███∙∙∙∙
    // ∙█████████████████∙
    // ∙█████████████████∙
    // ∙█████████████████∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙███∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙███∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙███∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙███∙∙∙∙
    0x1c, 0x0e, 0x03, 0x81, 0xc0, 0x70, 0x38, 0x0e, 0x07, 0x03, 0xc0, 0xe0, 0x70, 0x1c, 0x0e, 0x03, 0x81, 0xc0, 0x70, 0x78, 0x0e, 0x0f, 0xff, 0xf9, 0xff, 0xff, 0x3f, 0xff, 0xe0, 0x00, 0xe0, 0x00, 0x1c, 0x00, 0x03, 0x80, 0x00, 0x70
};
static const qymui::tImage HellenicaRus16px_0x34 = { image_data_HellenicaRus16px_0x34,
    19, 16, 8, 38};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x35[38] = {
    // ∙███████████████∙∙∙
    // ∙███████████████∙∙∙
    // ∙███████████████∙∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙█████████████∙∙∙∙∙
    // ∙███████████████∙∙∙
    // ∙███████████████∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙████∙∙
    // ∙███████████████∙∙∙
    // ∙███████████████∙∙∙
    // ∙█████████████∙∙∙∙∙
    0x7f, 0xff, 0x0f, 0xff, 0xe1, 0xff, 0xfc, 0x38, 0x00, 0x07, 0x00, 0x00, 0xe0, 0x00, 0x1f, 0xff, 0x03, 0xff, 0xf8, 0x7f, 0xff, 0x00, 0x00, 0xf0, 0x00, 0x0e, 0x00, 0x01, 0xc0, 0x00, 0x78, 0xff, 0xfe, 0x1f, 0xff, 0xc3, 0xff, 0xe0
};
static const qymui::tImage HellenicaRus16px_0x35 = { image_data_HellenicaRus16px_0x35,
    19, 16, 8, 38};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x36[38] = {
    // ∙∙∙∙████████████∙∙∙
    // ∙∙██████████████∙∙∙
    // ∙∙██████████████∙∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙█████████████∙∙∙∙∙
    // ∙███████████████∙∙∙
    // ∙███████████████∙∙∙
    // ∙████∙∙∙∙∙∙∙∙████∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙████∙∙∙∙∙∙∙∙████∙∙
    // ∙∙██████████████∙∙∙
    // ∙∙██████████████∙∙∙
    // ∙∙∙∙██████████∙∙∙∙∙
    0x0f, 0xff, 0x07, 0xff, 0xe0, 0xff, 0xfc, 0x38, 0x00, 0x07, 0x00, 0x00, 0xe0, 0x00, 0x1f, 0xff, 0x03, 0xff, 0xf8, 0x7f, 0xff, 0x0f, 0x00, 0xf1, 0xc0, 0x0e, 0x38, 0x01, 0xc7, 0x80, 0x78, 0x7f, 0xfe, 0x0f, 0xff, 0xc0, 0x7f, 0xe0
};
static const qymui::tImage HellenicaRus16px_0x36 = { image_data_HellenicaRus16px_0x36,
    19, 16, 8, 38};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x37[36] = {
    // ∙████████████████∙
    // ∙███████████████∙∙
    // ∙███████████████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙████∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙████∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙████∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙███∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙████∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙████∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙████∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙████∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙████∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙████∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙████∙∙∙∙∙∙∙∙∙∙
    0x7f, 0xff, 0x9f, 0xff, 0xc7, 0xff, 0xf0, 0x00, 0x78, 0x00, 0x1e, 0x00, 0x0f, 0x00, 0x03, 0x80, 0x01, 0xe0, 0x00, 0xf0, 0x00, 0x3c, 0x00, 0x1e, 0x00, 0x07, 0x00, 0x03, 0xc0, 0x01, 0xe0, 0x00, 0x78, 0x00, 0x3c, 0x00
};
static const qymui::tImage HellenicaRus16px_0x37 = { image_data_HellenicaRus16px_0x37,
    18, 16, 8, 36};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x38[38] = {
    // ∙∙∙∙██████████∙∙∙∙∙
    // ∙∙██████████████∙∙∙
    // ∙∙██████████████∙∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙████████████████∙∙
    // ∙∙██████████████∙∙∙
    // ∙∙██████████████∙∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙████∙∙∙∙∙∙∙∙████∙∙
    // ∙∙██████████████∙∙∙
    // ∙∙██████████████∙∙∙
    // ∙∙∙∙██████████∙∙∙∙∙
    0x0f, 0xfc, 0x07, 0xff, 0xe0, 0xff, 0xfc, 0x38, 0x01, 0xc7, 0x00, 0x38, 0xe0, 0x07, 0x1f, 0xff, 0xe1, 0xff, 0xf8, 0x3f, 0xff, 0x0e, 0x00, 0x71, 0xc0, 0x0e, 0x38, 0x01, 0xc7, 0x80, 0x78, 0x7f, 0xfe, 0x0f, 0xff, 0xc0, 0x7f, 0xe0
};
static const qymui::tImage HellenicaRus16px_0x38 = { image_data_HellenicaRus16px_0x38,
    19, 16, 8, 38};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0x39[38] = {
    // ∙∙∙∙██████████∙∙∙∙∙
    // ∙∙██████████████∙∙∙
    // ∙∙██████████████∙∙∙
    // ∙████∙∙∙∙∙∙∙∙████∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙███∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙████∙∙∙∙∙∙∙∙████∙∙
    // ∙∙███████████████∙∙
    // ∙∙███████████████∙∙
    // ∙∙∙∙█████████████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙∙██████████████∙∙∙
    // ∙∙██████████████∙∙∙
    // ∙∙████████████∙∙∙∙∙
    0x0f, 0xfc, 0x07, 0xff, 0xe0, 0xff, 0xfc, 0x3c, 0x03, 0xc7, 0x00, 0x38, 0xe0, 0x07, 0x1e, 0x01, 0xe1, 0xff, 0xfc, 0x3f, 0xff, 0x81, 0xff, 0xf0, 0x00, 0x0e, 0x00, 0x01, 0xc0, 0x00, 0x38, 0x7f, 0xfe, 0x0f, 0xff, 0xc1, 0xff, 0xe0
};
static const qymui::tImage HellenicaRus16px_0x39 = { image_data_HellenicaRus16px_0x39,
    19, 16, 8, 38};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus16px_0xc2b0[20] = {
    // ∙∙∙███∙∙∙∙
    // ∙∙█████∙∙∙
    // ∙██∙∙∙██∙∙
    // ∙██∙∙∙██∙∙
    // ∙██∙∙∙██∙∙
    // ∙∙█████∙∙∙
    // ∙∙∙███∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x1c, 0x0f, 0x86, 0x31, 0x8c, 0x63, 0x0f, 0x81, 0xc0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const qymui::tImage HellenicaRus16px_0xc2b0 = { image_data_HellenicaRus16px_0xc2b0,
    10, 16, 8, 20};
#endif


static const qymui::tChar HellenicaRus16px_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &HellenicaRus16px_0x20},
#else
  // character: ' ' == ''
  {0x20, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &HellenicaRus16px_0x21},
#else
  // character: '!' == ''
  {0x21, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &HellenicaRus16px_0x23},
#else
  // character: '#' == ''
  {0x23, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &HellenicaRus16px_0x2c},
#else
  // character: ',' == ''
  {0x2c, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &HellenicaRus16px_0x2e},
#else
  // character: '.' == ''
  {0x2e, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &HellenicaRus16px_0x30},
#else
  // character: '0' == ''
  {0x30, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &HellenicaRus16px_0x31},
#else
  // character: '1' == ''
  {0x31, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &HellenicaRus16px_0x32},
#else
  // character: '2' == ''
  {0x32, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &HellenicaRus16px_0x33},
#else
  // character: '3' == ''
  {0x33, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &HellenicaRus16px_0x34},
#else
  // character: '4' == ''
  {0x34, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &HellenicaRus16px_0x35},
#else
  // character: '5' == ''
  {0x35, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &HellenicaRus16px_0x36},
#else
  // character: '6' == ''
  {0x36, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &HellenicaRus16px_0x37},
#else
  // character: '7' == ''
  {0x37, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &HellenicaRus16px_0x38},
#else
  // character: '8' == ''
  {0x38, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &HellenicaRus16px_0x39},
#else
  // character: '9' == ''
  {0x39, &HellenicaRus16px_0x},
#endif

#if (0x0 == 0x0)
  // character: '°'
  {0xc2b0, &HellenicaRus16px_0xc2b0}
#else
  // character: '°' == ''
  {0xc2b0, &HellenicaRus16px_0x}
#endif

};


const qymui::tFont HellenicaRus16px = { 16, HellenicaRus16px_array };
