#pragma once
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: /home/basson/Develop/Main/lic/converter/HellenicaRus8px.xml
* name: HellenicaRus8px
* family: Hellenica
* size: 10
* style: Regular
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяÆÅÄÃÂÁÀ°
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
*
* preset name: Monochrome_Font
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Threshold Dither 255
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     uint8_t dataLenght;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#include "../lib/qymui/types.hpp"



#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x20[3] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x00, 0x00, 0x00
};
static const qymui::tImage HellenicaRus8px_0x20 = { image_data_HellenicaRus8px_0x20,
    3, 8, 8, 3};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x21[4] = {
    // ∙█∙∙
    // ███∙
    // ███∙
    // ███∙
    // ∙█∙∙
    // ∙∙∙∙
    // ∙█∙∙
    // ∙∙∙∙
    0x4e, 0xee, 0x40, 0x40
};
static const qymui::tImage HellenicaRus8px_0x21 = { image_data_HellenicaRus8px_0x21,
    4, 8, 8, 4};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x22[4] = {
    // ∙∙∙∙
    // █∙█∙
    // █∙█∙
    // █∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x0a, 0xaa, 0x00, 0x00
};
static const qymui::tImage HellenicaRus8px_0x22 = { image_data_HellenicaRus8px_0x22,
    4, 8, 8, 4};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x23[6] = {
    // ∙█∙█∙∙
    // ∙█∙█∙∙
    // █████∙
    // ∙█∙█∙∙
    // █████∙
    // ∙█∙█∙∙
    // ∙█∙█∙∙
    // ∙∙∙∙∙∙
    0x51, 0x4f, 0x94, 0xf9, 0x45, 0x00
};
static const qymui::tImage HellenicaRus8px_0x23 = { image_data_HellenicaRus8px_0x23,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x24[8] = {
    // ∙∙█∙█∙∙∙
    // ∙██████∙
    // █∙█∙█∙∙∙
    // ∙█████∙∙
    // ∙∙█∙█∙█∙
    // ██████∙∙
    // ∙∙█∙█∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x28, 0x7e, 0xa8, 0x7c, 0x2a, 0xfc, 0x28, 0x00
};
static const qymui::tImage HellenicaRus8px_0x24 = { image_data_HellenicaRus8px_0x24,
    8, 8, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x25[6] = {
    // ∙██∙∙∙
    // ∙██∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ∙∙∙∙∙∙
    // ∙∙∙██∙
    // ∙∙∙██∙
    // ∙∙∙∙∙∙
    0x61, 0x80, 0x1e, 0x00, 0x61, 0x80
};
static const qymui::tImage HellenicaRus8px_0x25 = { image_data_HellenicaRus8px_0x25,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x26[8] = {
    // ∙∙█████∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    0x3e, 0x40, 0x40, 0x7e, 0x24, 0x24, 0x3c, 0x00
};
static const qymui::tImage HellenicaRus8px_0x26 = { image_data_HellenicaRus8px_0x26,
    8, 8, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x27[2] = {
    // ∙∙
    // █∙
    // █∙
    // █∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    0x2a, 0x00
};
static const qymui::tImage HellenicaRus8px_0x27 = { image_data_HellenicaRus8px_0x27,
    2, 8, 8, 2};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x28[4] = {
    // ∙∙█∙
    // ∙█∙∙
    // █∙∙∙
    // █∙∙∙
    // █∙∙∙
    // ∙█∙∙
    // ∙∙█∙
    // ∙∙∙∙
    0x24, 0x88, 0x84, 0x20
};
static const qymui::tImage HellenicaRus8px_0x28 = { image_data_HellenicaRus8px_0x28,
    4, 8, 8, 4};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x29[4] = {
    // █∙∙∙
    // ∙█∙∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙█∙∙
    // █∙∙∙
    // ∙∙∙∙
    0x84, 0x22, 0x24, 0x80
};
static const qymui::tImage HellenicaRus8px_0x29 = { image_data_HellenicaRus8px_0x29,
    4, 8, 8, 4};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x2a[4] = {
    // ∙█∙∙
    // ███∙
    // ∙█∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x4e, 0x40, 0x00, 0x00
};
static const qymui::tImage HellenicaRus8px_0x2a = { image_data_HellenicaRus8px_0x2a,
    4, 8, 8, 4};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x2b[8] = {
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ███████∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x10, 0x10, 0x10, 0xfe, 0x10, 0x10, 0x10, 0x00
};
static const qymui::tImage HellenicaRus8px_0x2b = { image_data_HellenicaRus8px_0x2b,
    8, 8, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x2c[2] = {
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // █∙
    // █∙
    0x00, 0x0a
};
static const qymui::tImage HellenicaRus8px_0x2c = { image_data_HellenicaRus8px_0x2c,
    2, 8, 8, 2};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x2d[7] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ██████∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 0x00, 0x07, 0xe0, 0x00, 0x00, 0x00
};
static const qymui::tImage HellenicaRus8px_0x2d = { image_data_HellenicaRus8px_0x2d,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x2e[2] = {
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // █∙
    // ∙∙
    0x00, 0x08
};
static const qymui::tImage HellenicaRus8px_0x2e = { image_data_HellenicaRus8px_0x2e,
    2, 8, 8, 2};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x2f[7] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙█∙∙
    // ∙∙∙█∙∙∙
    // ∙∙█∙∙∙∙
    // ∙█∙∙∙∙∙
    // █∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 0x08, 0x20, 0x82, 0x08, 0x20, 0x00
};
static const qymui::tImage HellenicaRus8px_0x2f = { image_data_HellenicaRus8px_0x2f,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x30[7] = {
    // ∙∙██∙∙∙
    // ∙█∙∙█∙∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ∙█∙∙█∙∙
    // ∙∙██∙∙∙
    // ∙∙∙∙∙∙∙
    0x30, 0x92, 0x14, 0x28, 0x49, 0x0c, 0x00
};
static const qymui::tImage HellenicaRus8px_0x30 = { image_data_HellenicaRus8px_0x30,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x31[6] = {
    // ███∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // █████∙
    // ∙∙∙∙∙∙
    0xe0, 0x82, 0x08, 0x20, 0x8f, 0x80
};
static const qymui::tImage HellenicaRus8px_0x31 = { image_data_HellenicaRus8px_0x31,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x32[6] = {
    // █████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙████∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █████∙
    // ∙∙∙∙∙∙
    0xf8, 0x20, 0x9e, 0x82, 0x0f, 0x80
};
static const qymui::tImage HellenicaRus8px_0x32 = { image_data_HellenicaRus8px_0x32,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x33[6] = {
    // █████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // █████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // █████∙
    // ∙∙∙∙∙∙
    0xf8, 0x20, 0xbe, 0x08, 0x2f, 0x80
};
static const qymui::tImage HellenicaRus8px_0x33 = { image_data_HellenicaRus8px_0x33,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x34[6] = {
    // █∙∙█∙∙
    // █∙∙█∙∙
    // █∙∙█∙∙
    // █∙∙█∙∙
    // █████∙
    // ∙∙∙█∙∙
    // ∙∙∙█∙∙
    // ∙∙∙∙∙∙
    0x92, 0x49, 0x24, 0xf8, 0x41, 0x00
};
static const qymui::tImage HellenicaRus8px_0x34 = { image_data_HellenicaRus8px_0x34,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x35[6] = {
    // █████∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // █████∙
    // ∙∙∙∙∙∙
    0xfa, 0x08, 0x3e, 0x08, 0x2f, 0x80
};
static const qymui::tImage HellenicaRus8px_0x35 = { image_data_HellenicaRus8px_0x35,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x36[6] = {
    // ∙████∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █████∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █████∙
    // ∙∙∙∙∙∙
    0x7a, 0x08, 0x3e, 0x8a, 0x2f, 0x80
};
static const qymui::tImage HellenicaRus8px_0x36 = { image_data_HellenicaRus8px_0x36,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x37[6] = {
    // █████∙
    // ∙∙∙∙█∙
    // ∙∙∙█∙∙
    // ∙∙█∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙∙∙∙∙∙
    0xf8, 0x21, 0x08, 0x41, 0x04, 0x00
};
static const qymui::tImage HellenicaRus8px_0x37 = { image_data_HellenicaRus8px_0x37,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x38[6] = {
    // ∙███∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙███∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x72, 0x28, 0x9c, 0x8a, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0x38 = { image_data_HellenicaRus8px_0x38,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x39[6] = {
    // ∙███∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x72, 0x28, 0x9e, 0x08, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0x39 = { image_data_HellenicaRus8px_0x39,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x3a[2] = {
    // ∙∙
    // █∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // █∙
    // ∙∙
    0x20, 0x08
};
static const qymui::tImage HellenicaRus8px_0x3a = { image_data_HellenicaRus8px_0x3a,
    2, 8, 8, 2};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x3b[2] = {
    // ∙∙
    // █∙
    // ∙∙
    // ∙∙
    // ∙∙
    // █∙
    // █∙
    // ∙∙
    0x20, 0x28
};
static const qymui::tImage HellenicaRus8px_0x3b = { image_data_HellenicaRus8px_0x3b,
    2, 8, 8, 2};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x3c[5] = {
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // █∙∙∙∙
    // ∙█∙∙∙
    // ∙∙█∙∙
    // ∙∙∙█∙
    // ∙∙∙∙∙
    0x11, 0x11, 0x04, 0x10, 0x40
};
static const qymui::tImage HellenicaRus8px_0x3c = { image_data_HellenicaRus8px_0x3c,
    5, 8, 8, 5};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x3d[6] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // █████∙
    // ∙∙∙∙∙∙
    // █████∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00, 0x0f, 0x80, 0xf8, 0x00, 0x00
};
static const qymui::tImage HellenicaRus8px_0x3d = { image_data_HellenicaRus8px_0x3d,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x3e[5] = {
    // █∙∙∙∙
    // ∙█∙∙∙
    // ∙∙█∙∙
    // ∙∙∙█∙
    // ∙∙█∙∙
    // ∙█∙∙∙
    // █∙∙∙∙
    // ∙∙∙∙∙
    0x82, 0x08, 0x22, 0x22, 0x00
};
static const qymui::tImage HellenicaRus8px_0x3e = { image_data_HellenicaRus8px_0x3e,
    5, 8, 8, 5};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x3f[8] = {
    // ∙█████∙∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // ∙∙∙∙██∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x7c, 0x82, 0x82, 0x0c, 0x10, 0x00, 0x10, 0x00
};
static const qymui::tImage HellenicaRus8px_0x3f = { image_data_HellenicaRus8px_0x3f,
    8, 8, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x40[7] = {
    // ∙████∙∙
    // █∙∙∙∙█∙
    // █∙██∙█∙
    // █∙█∙█∙∙
    // █∙██∙∙∙
    // █∙∙∙∙∙∙
    // ██████∙
    // ∙∙∙∙∙∙∙
    0x79, 0x0a, 0xd5, 0x4b, 0x10, 0x3f, 0x00
};
static const qymui::tImage HellenicaRus8px_0x40 = { image_data_HellenicaRus8px_0x40,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x41[6] = {
    // ∙∙█∙∙∙
    // ∙█∙█∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █████∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x21, 0x48, 0xa2, 0xfa, 0x28, 0x80
};
static const qymui::tImage HellenicaRus8px_0x41 = { image_data_HellenicaRus8px_0x41,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x42[6] = {
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // ∙∙∙∙∙∙
    0xf2, 0x28, 0xbc, 0x8a, 0x2f, 0x00
};
static const qymui::tImage HellenicaRus8px_0x42 = { image_data_HellenicaRus8px_0x42,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x43[6] = {
    // ∙███∙∙
    // █∙∙∙█∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x72, 0x28, 0x20, 0x82, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0x43 = { image_data_HellenicaRus8px_0x43,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x44[6] = {
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // ∙∙∙∙∙∙
    0xf2, 0x28, 0xa2, 0x8a, 0x2f, 0x00
};
static const qymui::tImage HellenicaRus8px_0x44 = { image_data_HellenicaRus8px_0x44,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x45[6] = {
    // █████∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ████∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █████∙
    // ∙∙∙∙∙∙
    0xfa, 0x08, 0x3c, 0x82, 0x0f, 0x80
};
static const qymui::tImage HellenicaRus8px_0x45 = { image_data_HellenicaRus8px_0x45,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x46[6] = {
    // █████∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ████∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ∙∙∙∙∙∙
    0xfa, 0x08, 0x3c, 0x82, 0x08, 0x00
};
static const qymui::tImage HellenicaRus8px_0x46 = { image_data_HellenicaRus8px_0x46,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x47[6] = {
    // ∙███∙∙
    // █∙∙∙█∙
    // █∙∙∙∙∙
    // █∙███∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x72, 0x28, 0x2e, 0x8a, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0x47 = { image_data_HellenicaRus8px_0x47,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x48[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █████∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x8a, 0x28, 0xbe, 0x8a, 0x28, 0x80
};
static const qymui::tImage HellenicaRus8px_0x48 = { image_data_HellenicaRus8px_0x48,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x49[4] = {
    // ███∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ███∙
    // ∙∙∙∙
    0xe4, 0x44, 0x44, 0xe0
};
static const qymui::tImage HellenicaRus8px_0x49 = { image_data_HellenicaRus8px_0x49,
    4, 8, 8, 4};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x4a[6] = {
    // ∙████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙█∙∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x78, 0x20, 0x82, 0x8a, 0x47, 0x00
};
static const qymui::tImage HellenicaRus8px_0x4a = { image_data_HellenicaRus8px_0x4a,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x4b[6] = {
    // █∙∙∙█∙
    // █∙∙█∙∙
    // █∙█∙∙∙
    // ██∙∙∙∙
    // █∙█∙∙∙
    // █∙∙█∙∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x8a, 0x4a, 0x30, 0xa2, 0x48, 0x80
};
static const qymui::tImage HellenicaRus8px_0x4b = { image_data_HellenicaRus8px_0x4b,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x4c[5] = {
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ████∙
    // ∙∙∙∙∙
    0x84, 0x21, 0x08, 0x43, 0xc0
};
static const qymui::tImage HellenicaRus8px_0x4c = { image_data_HellenicaRus8px_0x4c,
    5, 8, 8, 5};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x4d[7] = {
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ██∙∙██∙
    // █∙██∙█∙
    // █∙██∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    0x85, 0x0b, 0x35, 0xab, 0x50, 0xa1, 0x00
};
static const qymui::tImage HellenicaRus8px_0x4d = { image_data_HellenicaRus8px_0x4d,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x4e[7] = {
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ██∙∙∙█∙
    // █∙█∙∙█∙
    // █∙∙█∙█∙
    // █∙∙∙██∙
    // █∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    0x85, 0x0b, 0x15, 0x29, 0x51, 0xa1, 0x00
};
static const qymui::tImage HellenicaRus8px_0x4e = { image_data_HellenicaRus8px_0x4e,
    7, 8, 8, 7};
#endif

#if (0x030 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x4f[7] = {
    // ∙∙██∙∙∙
    // ∙█∙∙█∙∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ∙█∙∙█∙∙
    // ∙∙██∙∙∙
    // ∙∙∙∙∙∙∙
    0x30, 0x92, 0x14, 0x28, 0x49, 0x0c, 0x00
};
static const qymui::tImage HellenicaRus8px_0x4f = { image_data_HellenicaRus8px_0x4f,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x50[6] = {
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ∙∙∙∙∙∙
    0xf2, 0x28, 0xbc, 0x82, 0x08, 0x00
};
static const qymui::tImage HellenicaRus8px_0x50 = { image_data_HellenicaRus8px_0x50,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x51[7] = {
    // ∙∙██∙∙∙
    // ∙█∙∙█∙∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // █∙∙█∙█∙
    // ∙█∙∙█∙∙
    // ∙∙██∙█∙
    // ∙∙∙∙∙∙∙
    0x30, 0x92, 0x14, 0x29, 0x49, 0x0d, 0x00
};
static const qymui::tImage HellenicaRus8px_0x51 = { image_data_HellenicaRus8px_0x51,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x52[6] = {
    // █████∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █████∙
    // █∙█∙∙∙
    // █∙█∙∙∙
    // █∙∙██∙
    // ∙∙∙∙∙∙
    0xfa, 0x28, 0xbe, 0xa2, 0x89, 0x80
};
static const qymui::tImage HellenicaRus8px_0x52 = { image_data_HellenicaRus8px_0x52,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x53[6] = {
    // ∙████∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ∙████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ████∙∙
    // ∙∙∙∙∙∙
    0x7a, 0x08, 0x1e, 0x08, 0x2f, 0x00
};
static const qymui::tImage HellenicaRus8px_0x53 = { image_data_HellenicaRus8px_0x53,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x54[6] = {
    // █████∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙∙∙∙∙
    0xf8, 0x82, 0x08, 0x20, 0x82, 0x00
};
static const qymui::tImage HellenicaRus8px_0x54 = { image_data_HellenicaRus8px_0x54,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x55[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x8a, 0x28, 0xa2, 0x8a, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0x55 = { image_data_HellenicaRus8px_0x55,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x56[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙█∙█∙∙
    // ∙█∙█∙∙
    // ∙∙█∙∙∙
    // ∙∙∙∙∙∙
    0x8a, 0x28, 0xa2, 0x51, 0x42, 0x00
};
static const qymui::tImage HellenicaRus8px_0x56 = { image_data_HellenicaRus8px_0x56,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x57[8] = {
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙█∙∙█∙
    // █∙█∙█∙█∙
    // ██∙∙∙██∙
    // █∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    0x82, 0x82, 0x82, 0x92, 0xaa, 0xc6, 0x82, 0x00
};
static const qymui::tImage HellenicaRus8px_0x57 = { image_data_HellenicaRus8px_0x57,
    8, 8, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x58[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙█∙█∙∙
    // ∙∙█∙∙∙
    // ∙█∙█∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x8a, 0x25, 0x08, 0x52, 0x28, 0x80
};
static const qymui::tImage HellenicaRus8px_0x58 = { image_data_HellenicaRus8px_0x58,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x59[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x8a, 0x28, 0x9e, 0x08, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0x59 = { image_data_HellenicaRus8px_0x59,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x5a[6] = {
    // █████∙
    // ∙∙∙∙█∙
    // ∙∙∙█∙∙
    // ∙∙█∙∙∙
    // ∙█∙∙∙∙
    // █∙∙∙∙∙
    // █████∙
    // ∙∙∙∙∙∙
    0xf8, 0x21, 0x08, 0x42, 0x0f, 0x80
};
static const qymui::tImage HellenicaRus8px_0x5a = { image_data_HellenicaRus8px_0x5a,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x5b[3] = {
    // ██∙
    // █∙∙
    // █∙∙
    // █∙∙
    // █∙∙
    // █∙∙
    // ██∙
    // ∙∙∙
    0xd2, 0x49, 0x30
};
static const qymui::tImage HellenicaRus8px_0x5b = { image_data_HellenicaRus8px_0x5b,
    3, 8, 8, 3};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x5c[7] = {
    // ∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00
};
static const qymui::tImage HellenicaRus8px_0x5c = { image_data_HellenicaRus8px_0x5c,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x5d[3] = {
    // ██∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ██∙
    // ∙∙∙
    0xc9, 0x24, 0xb0
};
static const qymui::tImage HellenicaRus8px_0x5d = { image_data_HellenicaRus8px_0x5d,
    3, 8, 8, 3};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x5e[4] = {
    // ∙█∙∙
    // █∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x4a, 0x00, 0x00, 0x00
};
static const qymui::tImage HellenicaRus8px_0x5e = { image_data_HellenicaRus8px_0x5e,
    4, 8, 8, 4};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x5f[7] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ██████∙
    // ∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x3f, 0x00
};
static const qymui::tImage HellenicaRus8px_0x5f = { image_data_HellenicaRus8px_0x5f,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x60[3] = {
    // ∙∙∙
    // █∙∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x11, 0x00, 0x00
};
static const qymui::tImage HellenicaRus8px_0x60 = { image_data_HellenicaRus8px_0x60,
    3, 8, 8, 3};
#endif

#if (0x041 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x61[6] = {
    // ∙∙█∙∙∙
    // ∙█∙█∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █████∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x21, 0x48, 0xa2, 0xfa, 0x28, 0x80
};
static const qymui::tImage HellenicaRus8px_0x61 = { image_data_HellenicaRus8px_0x61,
    6, 8, 8, 6};
#endif

#if (0x042 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x62[6] = {
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // ∙∙∙∙∙∙
    0xf2, 0x28, 0xbc, 0x8a, 0x2f, 0x00
};
static const qymui::tImage HellenicaRus8px_0x62 = { image_data_HellenicaRus8px_0x62,
    6, 8, 8, 6};
#endif

#if (0x043 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x63[6] = {
    // ∙███∙∙
    // █∙∙∙█∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x72, 0x28, 0x20, 0x82, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0x63 = { image_data_HellenicaRus8px_0x63,
    6, 8, 8, 6};
#endif

#if (0x044 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x64[6] = {
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // ∙∙∙∙∙∙
    0xf2, 0x28, 0xa2, 0x8a, 0x2f, 0x00
};
static const qymui::tImage HellenicaRus8px_0x64 = { image_data_HellenicaRus8px_0x64,
    6, 8, 8, 6};
#endif

#if (0x045 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x65[6] = {
    // █████∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ████∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █████∙
    // ∙∙∙∙∙∙
    0xfa, 0x08, 0x3c, 0x82, 0x0f, 0x80
};
static const qymui::tImage HellenicaRus8px_0x65 = { image_data_HellenicaRus8px_0x65,
    6, 8, 8, 6};
#endif

#if (0x046 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x66[6] = {
    // █████∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ████∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ∙∙∙∙∙∙
    0xfa, 0x08, 0x3c, 0x82, 0x08, 0x00
};
static const qymui::tImage HellenicaRus8px_0x66 = { image_data_HellenicaRus8px_0x66,
    6, 8, 8, 6};
#endif

#if (0x047 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x67[6] = {
    // ∙███∙∙
    // █∙∙∙█∙
    // █∙∙∙∙∙
    // █∙███∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x72, 0x28, 0x2e, 0x8a, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0x67 = { image_data_HellenicaRus8px_0x67,
    6, 8, 8, 6};
#endif

#if (0x048 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x68[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █████∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x8a, 0x28, 0xbe, 0x8a, 0x28, 0x80
};
static const qymui::tImage HellenicaRus8px_0x68 = { image_data_HellenicaRus8px_0x68,
    6, 8, 8, 6};
#endif

#if (0x049 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x69[4] = {
    // ███∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ███∙
    // ∙∙∙∙
    0xe4, 0x44, 0x44, 0xe0
};
static const qymui::tImage HellenicaRus8px_0x69 = { image_data_HellenicaRus8px_0x69,
    4, 8, 8, 4};
#endif

#if (0x04a == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x6a[6] = {
    // ∙████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙█∙∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x78, 0x20, 0x82, 0x8a, 0x47, 0x00
};
static const qymui::tImage HellenicaRus8px_0x6a = { image_data_HellenicaRus8px_0x6a,
    6, 8, 8, 6};
#endif

#if (0x04b == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x6b[6] = {
    // █∙∙∙█∙
    // █∙∙█∙∙
    // █∙█∙∙∙
    // ██∙∙∙∙
    // █∙█∙∙∙
    // █∙∙█∙∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x8a, 0x4a, 0x30, 0xa2, 0x48, 0x80
};
static const qymui::tImage HellenicaRus8px_0x6b = { image_data_HellenicaRus8px_0x6b,
    6, 8, 8, 6};
#endif

#if (0x04c == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x6c[5] = {
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ████∙
    // ∙∙∙∙∙
    0x84, 0x21, 0x08, 0x43, 0xc0
};
static const qymui::tImage HellenicaRus8px_0x6c = { image_data_HellenicaRus8px_0x6c,
    5, 8, 8, 5};
#endif

#if (0x04d == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x6d[7] = {
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ██∙∙██∙
    // █∙██∙█∙
    // █∙██∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    0x85, 0x0b, 0x35, 0xab, 0x50, 0xa1, 0x00
};
static const qymui::tImage HellenicaRus8px_0x6d = { image_data_HellenicaRus8px_0x6d,
    7, 8, 8, 7};
#endif

#if (0x04e == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x6e[7] = {
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ██∙∙∙█∙
    // █∙█∙∙█∙
    // █∙∙█∙█∙
    // █∙∙∙██∙
    // █∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    0x85, 0x0b, 0x15, 0x29, 0x51, 0xa1, 0x00
};
static const qymui::tImage HellenicaRus8px_0x6e = { image_data_HellenicaRus8px_0x6e,
    7, 8, 8, 7};
#endif

#if (0x030 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x6f[7] = {
    // ∙∙██∙∙∙
    // ∙█∙∙█∙∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ∙█∙∙█∙∙
    // ∙∙██∙∙∙
    // ∙∙∙∙∙∙∙
    0x30, 0x92, 0x14, 0x28, 0x49, 0x0c, 0x00
};
static const qymui::tImage HellenicaRus8px_0x6f = { image_data_HellenicaRus8px_0x6f,
    7, 8, 8, 7};
#endif

#if (0x050 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x70[6] = {
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ∙∙∙∙∙∙
    0xf2, 0x28, 0xbc, 0x82, 0x08, 0x00
};
static const qymui::tImage HellenicaRus8px_0x70 = { image_data_HellenicaRus8px_0x70,
    6, 8, 8, 6};
#endif

#if (0x051 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x71[7] = {
    // ∙∙██∙∙∙
    // ∙█∙∙█∙∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // █∙∙█∙█∙
    // ∙█∙∙█∙∙
    // ∙∙██∙█∙
    // ∙∙∙∙∙∙∙
    0x30, 0x92, 0x14, 0x29, 0x49, 0x0d, 0x00
};
static const qymui::tImage HellenicaRus8px_0x71 = { image_data_HellenicaRus8px_0x71,
    7, 8, 8, 7};
#endif

#if (0x052 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x72[6] = {
    // █████∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █████∙
    // █∙█∙∙∙
    // █∙█∙∙∙
    // █∙∙██∙
    // ∙∙∙∙∙∙
    0xfa, 0x28, 0xbe, 0xa2, 0x89, 0x80
};
static const qymui::tImage HellenicaRus8px_0x72 = { image_data_HellenicaRus8px_0x72,
    6, 8, 8, 6};
#endif

#if (0x053 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x73[6] = {
    // ∙████∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ∙████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ████∙∙
    // ∙∙∙∙∙∙
    0x7a, 0x08, 0x1e, 0x08, 0x2f, 0x00
};
static const qymui::tImage HellenicaRus8px_0x73 = { image_data_HellenicaRus8px_0x73,
    6, 8, 8, 6};
#endif

#if (0x054 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x74[6] = {
    // █████∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙∙∙∙∙
    0xf8, 0x82, 0x08, 0x20, 0x82, 0x00
};
static const qymui::tImage HellenicaRus8px_0x74 = { image_data_HellenicaRus8px_0x74,
    6, 8, 8, 6};
#endif

#if (0x055 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x75[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x8a, 0x28, 0xa2, 0x8a, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0x75 = { image_data_HellenicaRus8px_0x75,
    6, 8, 8, 6};
#endif

#if (0x056 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x76[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙█∙█∙∙
    // ∙█∙█∙∙
    // ∙∙█∙∙∙
    // ∙∙∙∙∙∙
    0x8a, 0x28, 0xa2, 0x51, 0x42, 0x00
};
static const qymui::tImage HellenicaRus8px_0x76 = { image_data_HellenicaRus8px_0x76,
    6, 8, 8, 6};
#endif

#if (0x057 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x77[8] = {
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙█∙∙█∙
    // █∙█∙█∙█∙
    // ██∙∙∙██∙
    // █∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙
    0x82, 0x82, 0x82, 0x92, 0xaa, 0xc6, 0x82, 0x00
};
static const qymui::tImage HellenicaRus8px_0x77 = { image_data_HellenicaRus8px_0x77,
    8, 8, 8, 8};
#endif

#if (0x058 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x78[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙█∙█∙∙
    // ∙∙█∙∙∙
    // ∙█∙█∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x8a, 0x25, 0x08, 0x52, 0x28, 0x80
};
static const qymui::tImage HellenicaRus8px_0x78 = { image_data_HellenicaRus8px_0x78,
    6, 8, 8, 6};
#endif

#if (0x059 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x79[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x8a, 0x28, 0x9e, 0x08, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0x79 = { image_data_HellenicaRus8px_0x79,
    6, 8, 8, 6};
#endif

#if (0x05a == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x7a[6] = {
    // █████∙
    // ∙∙∙∙█∙
    // ∙∙∙█∙∙
    // ∙∙█∙∙∙
    // ∙█∙∙∙∙
    // █∙∙∙∙∙
    // █████∙
    // ∙∙∙∙∙∙
    0xf8, 0x21, 0x08, 0x42, 0x0f, 0x80
};
static const qymui::tImage HellenicaRus8px_0x7a = { image_data_HellenicaRus8px_0x7a,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x7b[4] = {
    // ∙██∙
    // ∙█∙∙
    // ∙█∙∙
    // ██∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙██∙
    // ∙∙∙∙
    0x64, 0x4c, 0x44, 0x60
};
static const qymui::tImage HellenicaRus8px_0x7b = { image_data_HellenicaRus8px_0x7b,
    4, 8, 8, 4};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x7c[2] = {
    // █∙
    // █∙
    // █∙
    // █∙
    // █∙
    // █∙
    // █∙
    // █∙
    0xaa, 0xaa
};
static const qymui::tImage HellenicaRus8px_0x7c = { image_data_HellenicaRus8px_0x7c,
    2, 8, 8, 2};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x7d[4] = {
    // ∙██∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙██
    // ∙∙█∙
    // ∙∙█∙
    // ∙██∙
    // ∙∙∙∙
    0x62, 0x23, 0x22, 0x60
};
static const qymui::tImage HellenicaRus8px_0x7d = { image_data_HellenicaRus8px_0x7d,
    4, 8, 8, 4};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0x7e[7] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙██∙∙█∙
    // █∙∙██∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 0x00, 0x03, 0x29, 0x80, 0x00, 0x00
};
static const qymui::tImage HellenicaRus8px_0x7e = { image_data_HellenicaRus8px_0x7e,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xc2b0[5] = {
    // ∙███∙
    // ∙█∙█∙
    // ∙███∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x72, 0x9c, 0x00, 0x00, 0x00
};
static const qymui::tImage HellenicaRus8px_0xc2b0 = { image_data_HellenicaRus8px_0xc2b0,
    5, 8, 8, 5};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xc380[8] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const qymui::tImage HellenicaRus8px_0xc380 = { image_data_HellenicaRus8px_0xc380,
    8, 8, 8, 8};
#endif

#if (0x0c380 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xc381[8] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const qymui::tImage HellenicaRus8px_0xc381 = { image_data_HellenicaRus8px_0xc381,
    8, 8, 8, 8};
#endif

#if (0x0c380 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xc382[8] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const qymui::tImage HellenicaRus8px_0xc382 = { image_data_HellenicaRus8px_0xc382,
    8, 8, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xc383[7] = {
    // ∙∙██∙∙∙
    // ∙█∙∙█∙∙
    // █∙∙∙∙█∙
    // █∙∙∙██∙
    // █∙∙███∙
    // █∙██∙█∙
    // ∙████∙∙
    // ∙∙∙∙∙∙∙
    0x30, 0x92, 0x14, 0x69, 0xd6, 0x9e, 0x00
};
static const qymui::tImage HellenicaRus8px_0xc383 = { image_data_HellenicaRus8px_0xc383,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xc384[9] = {
    // ███∙∙███∙
    // █∙█∙∙█∙█∙
    // █∙████∙█∙
    // █∙∙∙∙∙∙█∙
    // ∙██∙∙██∙∙
    // ∙∙████∙∙∙
    // ∙∙∙██∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0xe7, 0x52, 0xaf, 0x50, 0x26, 0x61, 0xe0, 0x60, 0x00
};
static const qymui::tImage HellenicaRus8px_0xc384 = { image_data_HellenicaRus8px_0xc384,
    9, 8, 8, 9};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xc385[7] = {
    // ∙∙██∙∙∙
    // ∙██∙∙∙∙
    // ██∙∙∙∙∙
    // ██████∙
    // ∙∙∙∙██∙
    // ∙∙∙██∙∙
    // ∙∙██∙∙∙
    // ∙∙∙∙∙∙∙
    0x30, 0xc3, 0x07, 0xe0, 0xc3, 0x0c, 0x00
};
static const qymui::tImage HellenicaRus8px_0xc385 = { image_data_HellenicaRus8px_0xc385,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xc386[7] = {
    // ∙∙██∙∙∙
    // ∙█∙∙█∙∙
    // █∙∙∙∙█∙
    // █∙██∙█∙
    // █∙∙█∙█∙
    // ∙█∙∙█∙∙
    // ∙∙██∙∙∙
    // ∙∙∙∙∙∙∙
    0x30, 0x92, 0x15, 0xa9, 0x49, 0x0c, 0x00
};
static const qymui::tImage HellenicaRus8px_0xc386 = { image_data_HellenicaRus8px_0xc386,
    7, 8, 8, 7};
#endif

#if (0x041 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd090[6] = {
    // ∙∙█∙∙∙
    // ∙█∙█∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █████∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x21, 0x48, 0xa2, 0xfa, 0x28, 0x80
};
static const qymui::tImage HellenicaRus8px_0xd090 = { image_data_HellenicaRus8px_0xd090,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd091[6] = {
    // █████∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // ∙∙∙∙∙∙
    0xfa, 0x08, 0x3c, 0x8a, 0x2f, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd091 = { image_data_HellenicaRus8px_0xd091,
    6, 8, 8, 6};
#endif

#if (0x042 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd092[6] = {
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // ∙∙∙∙∙∙
    0xf2, 0x28, 0xbc, 0x8a, 0x2f, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd092 = { image_data_HellenicaRus8px_0xd092,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd093[5] = {
    // ████∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ∙∙∙∙∙
    0xf4, 0x21, 0x08, 0x42, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd093 = { image_data_HellenicaRus8px_0xd093,
    5, 8, 8, 5};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd094[7] = {
    // ∙∙███∙∙
    // ∙█∙∙█∙∙
    // ∙█∙∙█∙∙
    // ∙█∙∙█∙∙
    // ∙█∙∙█∙∙
    // ∙█∙∙█∙∙
    // ██████∙
    // █∙∙∙∙█∙
    0x38, 0x91, 0x22, 0x44, 0x89, 0x3f, 0x42
};
static const qymui::tImage HellenicaRus8px_0xd094 = { image_data_HellenicaRus8px_0xd094,
    7, 8, 8, 7};
#endif

#if (0x045 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd095[6] = {
    // █████∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ████∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █████∙
    // ∙∙∙∙∙∙
    0xfa, 0x08, 0x3c, 0x82, 0x0f, 0x80
};
static const qymui::tImage HellenicaRus8px_0xd095 = { image_data_HellenicaRus8px_0xd095,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd096[10] = {
    // █∙∙∙█∙∙∙█∙
    // ∙█∙∙█∙∙█∙∙
    // ∙∙█∙█∙█∙∙∙
    // ∙∙∙███∙∙∙∙
    // ∙∙█∙█∙█∙∙∙
    // ∙█∙∙█∙∙█∙∙
    // █∙∙∙█∙∙∙█∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x88, 0x92, 0x42, 0xa0, 0x70, 0x2a, 0x12, 0x48, 0x88, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd096 = { image_data_HellenicaRus8px_0xd096,
    10, 8, 8, 10};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd097[5] = {
    // ████∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ███∙∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ████∙
    // ∙∙∙∙∙
    0xf0, 0x85, 0xc1, 0x0b, 0xc0
};
static const qymui::tImage HellenicaRus8px_0xd097 = { image_data_HellenicaRus8px_0xd097,
    5, 8, 8, 5};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd098[7] = {
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙██∙
    // █∙∙█∙█∙
    // █∙█∙∙█∙
    // ██∙∙∙█∙
    // █∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    0x85, 0x0a, 0x34, 0xaa, 0x58, 0xa1, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd098 = { image_data_HellenicaRus8px_0xd098,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd099[7] = {
    // █∙██∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙██∙
    // █∙∙█∙█∙
    // █∙█∙∙█∙
    // ██∙∙∙█∙
    // █∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    0xb5, 0x0a, 0x34, 0xaa, 0x58, 0xa1, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd099 = { image_data_HellenicaRus8px_0xd099,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd09a[7] = {
    // █∙∙∙∙█∙
    // █∙∙∙█∙∙
    // █∙∙█∙∙∙
    // ███∙∙∙∙
    // █∙∙█∙∙∙
    // █∙∙∙█∙∙
    // █∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    0x85, 0x12, 0x47, 0x09, 0x11, 0x21, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd09a = { image_data_HellenicaRus8px_0xd09a,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd09b[6] = {
    // ∙∙███∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ██∙∙█∙
    // ∙∙∙∙∙∙
    0x39, 0x24, 0x92, 0x49, 0x2c, 0x80
};
static const qymui::tImage HellenicaRus8px_0xd09b = { image_data_HellenicaRus8px_0xd09b,
    6, 8, 8, 6};
#endif

#if (0x04d == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd09c[7] = {
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ██∙∙██∙
    // █∙██∙█∙
    // █∙██∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    0x85, 0x0b, 0x35, 0xab, 0x50, 0xa1, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd09c = { image_data_HellenicaRus8px_0xd09c,
    7, 8, 8, 7};
#endif

#if (0x048 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd09d[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █████∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x8a, 0x28, 0xbe, 0x8a, 0x28, 0x80
};
static const qymui::tImage HellenicaRus8px_0xd09d = { image_data_HellenicaRus8px_0xd09d,
    6, 8, 8, 6};
#endif

#if (0x030 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd09e[7] = {
    // ∙∙██∙∙∙
    // ∙█∙∙█∙∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ∙█∙∙█∙∙
    // ∙∙██∙∙∙
    // ∙∙∙∙∙∙∙
    0x30, 0x92, 0x14, 0x28, 0x49, 0x0c, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd09e = { image_data_HellenicaRus8px_0xd09e,
    7, 8, 8, 7};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd09f[5] = {
    // ████∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    0xf4, 0xa5, 0x29, 0x4a, 0x40
};
static const qymui::tImage HellenicaRus8px_0xd09f = { image_data_HellenicaRus8px_0xd09f,
    5, 8, 8, 5};
#endif

#if (0x050 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0a0[6] = {
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ∙∙∙∙∙∙
    0xf2, 0x28, 0xbc, 0x82, 0x08, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0a0 = { image_data_HellenicaRus8px_0xd0a0,
    6, 8, 8, 6};
#endif

#if (0x043 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0a1[6] = {
    // ∙███∙∙
    // █∙∙∙█∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x72, 0x28, 0x20, 0x82, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0a1 = { image_data_HellenicaRus8px_0xd0a1,
    6, 8, 8, 6};
#endif

#if (0x054 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0a2[6] = {
    // █████∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙∙∙∙∙
    0xf8, 0x82, 0x08, 0x20, 0x82, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0a2 = { image_data_HellenicaRus8px_0xd0a2,
    6, 8, 8, 6};
#endif

#if (0x059 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0a3[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x8a, 0x28, 0x9e, 0x08, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0a3 = { image_data_HellenicaRus8px_0xd0a3,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0a4[8] = {
    // ∙█████∙∙
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // ∙█████∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x7c, 0x92, 0x92, 0x92, 0x7c, 0x10, 0x10, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0a4 = { image_data_HellenicaRus8px_0xd0a4,
    8, 8, 8, 8};
#endif

#if (0x058 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0a5[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙█∙█∙∙
    // ∙∙█∙∙∙
    // ∙█∙█∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x8a, 0x25, 0x08, 0x52, 0x28, 0x80
};
static const qymui::tImage HellenicaRus8px_0xd0a5 = { image_data_HellenicaRus8px_0xd0a5,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0a6[6] = {
    // █∙∙█∙∙
    // █∙∙█∙∙
    // █∙∙█∙∙
    // █∙∙█∙∙
    // █∙∙█∙∙
    // █∙∙█∙∙
    // █████∙
    // ∙∙∙∙█∙
    0x92, 0x49, 0x24, 0x92, 0x4f, 0x82
};
static const qymui::tImage HellenicaRus8px_0xd0a6 = { image_data_HellenicaRus8px_0xd0a6,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0a7[5] = {
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙███∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙∙∙∙∙
    0x94, 0xa5, 0x27, 0x08, 0x40
};
static const qymui::tImage HellenicaRus8px_0xd0a7 = { image_data_HellenicaRus8px_0xd0a7,
    5, 8, 8, 5};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0a8[8] = {
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // ███████∙
    // ∙∙∙∙∙∙∙∙
    0x92, 0x92, 0x92, 0x92, 0x92, 0x92, 0xfe, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0a8 = { image_data_HellenicaRus8px_0xd0a8,
    8, 8, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0a9[9] = {
    // █∙∙█∙∙█∙∙
    // █∙∙█∙∙█∙∙
    // █∙∙█∙∙█∙∙
    // █∙∙█∙∙█∙∙
    // █∙∙█∙∙█∙∙
    // █∙∙█∙∙█∙∙
    // ████████∙
    // ∙∙∙∙∙∙∙█∙
    0x92, 0x49, 0x24, 0x92, 0x49, 0x24, 0x93, 0xfc, 0x02
};
static const qymui::tImage HellenicaRus8px_0xd0a9 = { image_data_HellenicaRus8px_0xd0a9,
    9, 8, 8, 9};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0aa[8] = {
    // ███∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙████∙∙
    // ∙∙█∙∙∙█∙
    // ∙∙█∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    0xe0, 0x20, 0x20, 0x3c, 0x22, 0x22, 0x3c, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0aa = { image_data_HellenicaRus8px_0xd0aa,
    8, 8, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0ab[8] = {
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // ████∙∙█∙
    // █∙∙∙█∙█∙
    // █∙∙∙█∙█∙
    // ████∙∙█∙
    // ∙∙∙∙∙∙∙∙
    0x82, 0x82, 0x82, 0xf2, 0x8a, 0x8a, 0xf2, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0ab = { image_data_HellenicaRus8px_0xd0ab,
    8, 8, 8, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0ac[6] = {
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // ∙∙∙∙∙∙
    0x82, 0x08, 0x3c, 0x8a, 0x2f, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0ac = { image_data_HellenicaRus8px_0xd0ac,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0ad[6] = {
    // ∙███∙∙
    // █∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙████∙
    // ∙∙∙∙█∙
    // █∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x72, 0x20, 0x9e, 0x0a, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0ad = { image_data_HellenicaRus8px_0xd0ad,
    6, 8, 8, 6};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0ae[9] = {
    // █∙∙████∙∙
    // █∙██∙∙██∙
    // █∙█∙∙∙∙█∙
    // ███∙∙∙∙█∙
    // █∙█∙∙∙∙█∙
    // █∙██∙∙██∙
    // █∙∙████∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x9e, 0x59, 0xa8, 0x5c, 0x2a, 0x15, 0x9a, 0x78, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0ae = { image_data_HellenicaRus8px_0xd0ae,
    9, 8, 8, 9};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0af[6] = {
    // ∙████∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙████∙
    // ∙∙█∙█∙
    // ∙∙█∙█∙
    // ██∙∙█∙
    // ∙∙∙∙∙∙
    0x7a, 0x28, 0x9e, 0x28, 0xac, 0x80
};
static const qymui::tImage HellenicaRus8px_0xd0af = { image_data_HellenicaRus8px_0xd0af,
    6, 8, 8, 6};
#endif

#if (0x041 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0b0[6] = {
    // ∙∙█∙∙∙
    // ∙█∙█∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █████∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x21, 0x48, 0xa2, 0xfa, 0x28, 0x80
};
static const qymui::tImage HellenicaRus8px_0xd0b0 = { image_data_HellenicaRus8px_0xd0b0,
    6, 8, 8, 6};
#endif

#if (0x0d091 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0b1[6] = {
    // █████∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // ∙∙∙∙∙∙
    0xfa, 0x08, 0x3c, 0x8a, 0x2f, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0b1 = { image_data_HellenicaRus8px_0xd0b1,
    6, 8, 8, 6};
#endif

#if (0x042 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0b2[6] = {
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // ∙∙∙∙∙∙
    0xf2, 0x28, 0xbc, 0x8a, 0x2f, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0b2 = { image_data_HellenicaRus8px_0xd0b2,
    6, 8, 8, 6};
#endif

#if (0x0d093 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0b3[5] = {
    // ████∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // █∙∙∙∙
    // ∙∙∙∙∙
    0xf4, 0x21, 0x08, 0x42, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0b3 = { image_data_HellenicaRus8px_0xd0b3,
    5, 8, 8, 5};
#endif

#if (0x0d094 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0b4[7] = {
    // ∙∙███∙∙
    // ∙█∙∙█∙∙
    // ∙█∙∙█∙∙
    // ∙█∙∙█∙∙
    // ∙█∙∙█∙∙
    // ∙█∙∙█∙∙
    // ██████∙
    // █∙∙∙∙█∙
    0x38, 0x91, 0x22, 0x44, 0x89, 0x3f, 0x42
};
static const qymui::tImage HellenicaRus8px_0xd0b4 = { image_data_HellenicaRus8px_0xd0b4,
    7, 8, 8, 7};
#endif

#if (0x045 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0b5[6] = {
    // █████∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ████∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █████∙
    // ∙∙∙∙∙∙
    0xfa, 0x08, 0x3c, 0x82, 0x0f, 0x80
};
static const qymui::tImage HellenicaRus8px_0xd0b5 = { image_data_HellenicaRus8px_0xd0b5,
    6, 8, 8, 6};
#endif

#if (0x0d096 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0b6[10] = {
    // █∙∙∙█∙∙∙█∙
    // ∙█∙∙█∙∙█∙∙
    // ∙∙█∙█∙█∙∙∙
    // ∙∙∙███∙∙∙∙
    // ∙∙█∙█∙█∙∙∙
    // ∙█∙∙█∙∙█∙∙
    // █∙∙∙█∙∙∙█∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x88, 0x92, 0x42, 0xa0, 0x70, 0x2a, 0x12, 0x48, 0x88, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0b6 = { image_data_HellenicaRus8px_0xd0b6,
    10, 8, 8, 10};
#endif

#if (0x0d097 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0b7[5] = {
    // ████∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ███∙∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ████∙
    // ∙∙∙∙∙
    0xf0, 0x85, 0xc1, 0x0b, 0xc0
};
static const qymui::tImage HellenicaRus8px_0xd0b7 = { image_data_HellenicaRus8px_0xd0b7,
    5, 8, 8, 5};
#endif

#if (0x0d098 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0b8[7] = {
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙██∙
    // █∙∙█∙█∙
    // █∙█∙∙█∙
    // ██∙∙∙█∙
    // █∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    0x85, 0x0a, 0x34, 0xaa, 0x58, 0xa1, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0b8 = { image_data_HellenicaRus8px_0xd0b8,
    7, 8, 8, 7};
#endif

#if (0x0d099 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0b9[7] = {
    // █∙██∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙██∙
    // █∙∙█∙█∙
    // █∙█∙∙█∙
    // ██∙∙∙█∙
    // █∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    0xb5, 0x0a, 0x34, 0xaa, 0x58, 0xa1, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0b9 = { image_data_HellenicaRus8px_0xd0b9,
    7, 8, 8, 7};
#endif

#if (0x0d09a == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0ba[7] = {
    // █∙∙∙∙█∙
    // █∙∙∙█∙∙
    // █∙∙█∙∙∙
    // ███∙∙∙∙
    // █∙∙█∙∙∙
    // █∙∙∙█∙∙
    // █∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    0x85, 0x12, 0x47, 0x09, 0x11, 0x21, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0ba = { image_data_HellenicaRus8px_0xd0ba,
    7, 8, 8, 7};
#endif

#if (0x0d09b == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0bb[6] = {
    // ∙∙███∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ██∙∙█∙
    // ∙∙∙∙∙∙
    0x39, 0x24, 0x92, 0x49, 0x2c, 0x80
};
static const qymui::tImage HellenicaRus8px_0xd0bb = { image_data_HellenicaRus8px_0xd0bb,
    6, 8, 8, 6};
#endif

#if (0x04d == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0bc[7] = {
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ██∙∙██∙
    // █∙██∙█∙
    // █∙██∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    0x85, 0x0b, 0x35, 0xab, 0x50, 0xa1, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0bc = { image_data_HellenicaRus8px_0xd0bc,
    7, 8, 8, 7};
#endif

#if (0x048 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0bd[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █████∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x8a, 0x28, 0xbe, 0x8a, 0x28, 0x80
};
static const qymui::tImage HellenicaRus8px_0xd0bd = { image_data_HellenicaRus8px_0xd0bd,
    6, 8, 8, 6};
#endif

#if (0x030 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0be[7] = {
    // ∙∙██∙∙∙
    // ∙█∙∙█∙∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // █∙∙∙∙█∙
    // ∙█∙∙█∙∙
    // ∙∙██∙∙∙
    // ∙∙∙∙∙∙∙
    0x30, 0x92, 0x14, 0x28, 0x49, 0x0c, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd0be = { image_data_HellenicaRus8px_0xd0be,
    7, 8, 8, 7};
#endif

#if (0x0d09f == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd0bf[5] = {
    // ████∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙∙∙∙∙
    0xf4, 0xa5, 0x29, 0x4a, 0x40
};
static const qymui::tImage HellenicaRus8px_0xd0bf = { image_data_HellenicaRus8px_0xd0bf,
    5, 8, 8, 5};
#endif

#if (0x050 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd180[6] = {
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ∙∙∙∙∙∙
    0xf2, 0x28, 0xbc, 0x82, 0x08, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd180 = { image_data_HellenicaRus8px_0xd180,
    6, 8, 8, 6};
#endif

#if (0x043 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd181[6] = {
    // ∙███∙∙
    // █∙∙∙█∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x72, 0x28, 0x20, 0x82, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd181 = { image_data_HellenicaRus8px_0xd181,
    6, 8, 8, 6};
#endif

#if (0x054 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd182[6] = {
    // █████∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙∙∙∙∙
    0xf8, 0x82, 0x08, 0x20, 0x82, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd182 = { image_data_HellenicaRus8px_0xd182,
    6, 8, 8, 6};
#endif

#if (0x059 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd183[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙████∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x8a, 0x28, 0x9e, 0x08, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd183 = { image_data_HellenicaRus8px_0xd183,
    6, 8, 8, 6};
#endif

#if (0x0d0a4 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd184[8] = {
    // ∙█████∙∙
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // ∙█████∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x7c, 0x92, 0x92, 0x92, 0x7c, 0x10, 0x10, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd184 = { image_data_HellenicaRus8px_0xd184,
    8, 8, 8, 8};
#endif

#if (0x058 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd185[6] = {
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙█∙█∙∙
    // ∙∙█∙∙∙
    // ∙█∙█∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙∙∙∙∙∙
    0x8a, 0x25, 0x08, 0x52, 0x28, 0x80
};
static const qymui::tImage HellenicaRus8px_0xd185 = { image_data_HellenicaRus8px_0xd185,
    6, 8, 8, 6};
#endif

#if (0x0d0a6 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd186[6] = {
    // █∙∙█∙∙
    // █∙∙█∙∙
    // █∙∙█∙∙
    // █∙∙█∙∙
    // █∙∙█∙∙
    // █∙∙█∙∙
    // █████∙
    // ∙∙∙∙█∙
    0x92, 0x49, 0x24, 0x92, 0x4f, 0x82
};
static const qymui::tImage HellenicaRus8px_0xd186 = { image_data_HellenicaRus8px_0xd186,
    6, 8, 8, 6};
#endif

#if (0x0d0a7 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd187[5] = {
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // █∙∙█∙
    // ∙███∙
    // ∙∙∙█∙
    // ∙∙∙█∙
    // ∙∙∙∙∙
    0x94, 0xa5, 0x27, 0x08, 0x40
};
static const qymui::tImage HellenicaRus8px_0xd187 = { image_data_HellenicaRus8px_0xd187,
    5, 8, 8, 5};
#endif

#if (0x0d0a8 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd188[8] = {
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // █∙∙█∙∙█∙
    // ███████∙
    // ∙∙∙∙∙∙∙∙
    0x92, 0x92, 0x92, 0x92, 0x92, 0x92, 0xfe, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd188 = { image_data_HellenicaRus8px_0xd188,
    8, 8, 8, 8};
#endif

#if (0x0d0a9 == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd189[9] = {
    // █∙∙█∙∙█∙∙
    // █∙∙█∙∙█∙∙
    // █∙∙█∙∙█∙∙
    // █∙∙█∙∙█∙∙
    // █∙∙█∙∙█∙∙
    // █∙∙█∙∙█∙∙
    // ████████∙
    // ∙∙∙∙∙∙∙█∙
    0x92, 0x49, 0x24, 0x92, 0x49, 0x24, 0x93, 0xfc, 0x02
};
static const qymui::tImage HellenicaRus8px_0xd189 = { image_data_HellenicaRus8px_0xd189,
    9, 8, 8, 9};
#endif

#if (0x0d0aa == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd18a[8] = {
    // ███∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙████∙∙
    // ∙∙█∙∙∙█∙
    // ∙∙█∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    0xe0, 0x20, 0x20, 0x3c, 0x22, 0x22, 0x3c, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd18a = { image_data_HellenicaRus8px_0xd18a,
    8, 8, 8, 8};
#endif

#if (0x0d0ab == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd18b[8] = {
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // █∙∙∙∙∙█∙
    // ████∙∙█∙
    // █∙∙∙█∙█∙
    // █∙∙∙█∙█∙
    // ████∙∙█∙
    // ∙∙∙∙∙∙∙∙
    0x82, 0x82, 0x82, 0xf2, 0x8a, 0x8a, 0xf2, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd18b = { image_data_HellenicaRus8px_0xd18b,
    8, 8, 8, 8};
#endif

#if (0x0d0ac == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd18c[6] = {
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // █∙∙∙∙∙
    // ████∙∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ████∙∙
    // ∙∙∙∙∙∙
    0x82, 0x08, 0x3c, 0x8a, 0x2f, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd18c = { image_data_HellenicaRus8px_0xd18c,
    6, 8, 8, 6};
#endif

#if (0x0d0ad == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd18d[6] = {
    // ∙███∙∙
    // █∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙████∙
    // ∙∙∙∙█∙
    // █∙∙∙█∙
    // ∙███∙∙
    // ∙∙∙∙∙∙
    0x72, 0x20, 0x9e, 0x0a, 0x27, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd18d = { image_data_HellenicaRus8px_0xd18d,
    6, 8, 8, 6};
#endif

#if (0x0d0ae == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd18e[9] = {
    // █∙∙████∙∙
    // █∙██∙∙██∙
    // █∙█∙∙∙∙█∙
    // ███∙∙∙∙█∙
    // █∙█∙∙∙∙█∙
    // █∙██∙∙██∙
    // █∙∙████∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x9e, 0x59, 0xa8, 0x5c, 0x2a, 0x15, 0x9a, 0x78, 0x00
};
static const qymui::tImage HellenicaRus8px_0xd18e = { image_data_HellenicaRus8px_0xd18e,
    9, 8, 8, 9};
#endif

#if (0x0d0af == 0x0)
static const uint8_t image_data_HellenicaRus8px_0xd18f[6] = {
    // ∙████∙
    // █∙∙∙█∙
    // █∙∙∙█∙
    // ∙████∙
    // ∙∙█∙█∙
    // ∙∙█∙█∙
    // ██∙∙█∙
    // ∙∙∙∙∙∙
    0x7a, 0x28, 0x9e, 0x28, 0xac, 0x80
};
static const qymui::tImage HellenicaRus8px_0xd18f = { image_data_HellenicaRus8px_0xd18f,
    6, 8, 8, 6};
#endif


static const qymui::tChar HellenicaRus8px_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &HellenicaRus8px_0x20},
#else
  // character: ' ' == ''
  {0x20, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &HellenicaRus8px_0x21},
#else
  // character: '!' == ''
  {0x21, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '"'
  {0x22, &HellenicaRus8px_0x22},
#else
  // character: '"' == ''
  {0x22, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &HellenicaRus8px_0x23},
#else
  // character: '#' == ''
  {0x23, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &HellenicaRus8px_0x24},
#else
  // character: '$' == ''
  {0x24, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &HellenicaRus8px_0x25},
#else
  // character: '%' == ''
  {0x25, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &HellenicaRus8px_0x26},
#else
  // character: '&' == ''
  {0x26, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '''
  {0x27, &HellenicaRus8px_0x27},
#else
  // character: ''' == ''
  {0x27, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &HellenicaRus8px_0x28},
#else
  // character: '(' == ''
  {0x28, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &HellenicaRus8px_0x29},
#else
  // character: ')' == ''
  {0x29, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &HellenicaRus8px_0x2a},
#else
  // character: '*' == ''
  {0x2a, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &HellenicaRus8px_0x2b},
#else
  // character: '+' == ''
  {0x2b, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &HellenicaRus8px_0x2c},
#else
  // character: ',' == ''
  {0x2c, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &HellenicaRus8px_0x2d},
#else
  // character: '-' == ''
  {0x2d, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &HellenicaRus8px_0x2e},
#else
  // character: '.' == ''
  {0x2e, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &HellenicaRus8px_0x2f},
#else
  // character: '/' == ''
  {0x2f, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &HellenicaRus8px_0x30},
#else
  // character: '0' == ''
  {0x30, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &HellenicaRus8px_0x31},
#else
  // character: '1' == ''
  {0x31, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &HellenicaRus8px_0x32},
#else
  // character: '2' == ''
  {0x32, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &HellenicaRus8px_0x33},
#else
  // character: '3' == ''
  {0x33, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &HellenicaRus8px_0x34},
#else
  // character: '4' == ''
  {0x34, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &HellenicaRus8px_0x35},
#else
  // character: '5' == ''
  {0x35, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &HellenicaRus8px_0x36},
#else
  // character: '6' == ''
  {0x36, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &HellenicaRus8px_0x37},
#else
  // character: '7' == ''
  {0x37, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &HellenicaRus8px_0x38},
#else
  // character: '8' == ''
  {0x38, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &HellenicaRus8px_0x39},
#else
  // character: '9' == ''
  {0x39, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &HellenicaRus8px_0x3a},
#else
  // character: ':' == ''
  {0x3a, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &HellenicaRus8px_0x3b},
#else
  // character: ';' == ''
  {0x3b, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &HellenicaRus8px_0x3c},
#else
  // character: '<' == ''
  {0x3c, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &HellenicaRus8px_0x3d},
#else
  // character: '=' == ''
  {0x3d, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &HellenicaRus8px_0x3e},
#else
  // character: '>' == ''
  {0x3e, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &HellenicaRus8px_0x3f},
#else
  // character: '?' == ''
  {0x3f, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x0040'
  {0x40, &HellenicaRus8px_0x40},
#else
  // character: '\x0040' == ''
  {0x40, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &HellenicaRus8px_0x41},
#else
  // character: 'A' == ''
  {0x41, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &HellenicaRus8px_0x42},
#else
  // character: 'B' == ''
  {0x42, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &HellenicaRus8px_0x43},
#else
  // character: 'C' == ''
  {0x43, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &HellenicaRus8px_0x44},
#else
  // character: 'D' == ''
  {0x44, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &HellenicaRus8px_0x45},
#else
  // character: 'E' == ''
  {0x45, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &HellenicaRus8px_0x46},
#else
  // character: 'F' == ''
  {0x46, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &HellenicaRus8px_0x47},
#else
  // character: 'G' == ''
  {0x47, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &HellenicaRus8px_0x48},
#else
  // character: 'H' == ''
  {0x48, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &HellenicaRus8px_0x49},
#else
  // character: 'I' == ''
  {0x49, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &HellenicaRus8px_0x4a},
#else
  // character: 'J' == ''
  {0x4a, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &HellenicaRus8px_0x4b},
#else
  // character: 'K' == ''
  {0x4b, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &HellenicaRus8px_0x4c},
#else
  // character: 'L' == ''
  {0x4c, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &HellenicaRus8px_0x4d},
#else
  // character: 'M' == ''
  {0x4d, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &HellenicaRus8px_0x4e},
#else
  // character: 'N' == ''
  {0x4e, &HellenicaRus8px_0x},
#endif

#if (0x030 == 0x0)
  // character: 'O'
  {0x4f, &HellenicaRus8px_0x4f},
#else
  // character: 'O' == '0'
  {0x4f, &HellenicaRus8px_0x30},
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &HellenicaRus8px_0x50},
#else
  // character: 'P' == ''
  {0x50, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &HellenicaRus8px_0x51},
#else
  // character: 'Q' == ''
  {0x51, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &HellenicaRus8px_0x52},
#else
  // character: 'R' == ''
  {0x52, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &HellenicaRus8px_0x53},
#else
  // character: 'S' == ''
  {0x53, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &HellenicaRus8px_0x54},
#else
  // character: 'T' == ''
  {0x54, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &HellenicaRus8px_0x55},
#else
  // character: 'U' == ''
  {0x55, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &HellenicaRus8px_0x56},
#else
  // character: 'V' == ''
  {0x56, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &HellenicaRus8px_0x57},
#else
  // character: 'W' == ''
  {0x57, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &HellenicaRus8px_0x58},
#else
  // character: 'X' == ''
  {0x58, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &HellenicaRus8px_0x59},
#else
  // character: 'Y' == ''
  {0x59, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &HellenicaRus8px_0x5a},
#else
  // character: 'Z' == ''
  {0x5a, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &HellenicaRus8px_0x5b},
#else
  // character: '[' == ''
  {0x5b, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &HellenicaRus8px_0x5c},
#else
  // character: '\' == ''
  {0x5c, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &HellenicaRus8px_0x5d},
#else
  // character: ']' == ''
  {0x5d, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &HellenicaRus8px_0x5e},
#else
  // character: '^' == ''
  {0x5e, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &HellenicaRus8px_0x5f},
#else
  // character: '_' == ''
  {0x5f, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &HellenicaRus8px_0x60},
#else
  // character: '`' == ''
  {0x60, &HellenicaRus8px_0x},
#endif

#if (0x041 == 0x0)
  // character: 'a'
  {0x61, &HellenicaRus8px_0x61},
#else
  // character: 'a' == 'A'
  {0x61, &HellenicaRus8px_0x41},
#endif

#if (0x042 == 0x0)
  // character: 'b'
  {0x62, &HellenicaRus8px_0x62},
#else
  // character: 'b' == 'B'
  {0x62, &HellenicaRus8px_0x42},
#endif

#if (0x043 == 0x0)
  // character: 'c'
  {0x63, &HellenicaRus8px_0x63},
#else
  // character: 'c' == 'C'
  {0x63, &HellenicaRus8px_0x43},
#endif

#if (0x044 == 0x0)
  // character: 'd'
  {0x64, &HellenicaRus8px_0x64},
#else
  // character: 'd' == 'D'
  {0x64, &HellenicaRus8px_0x44},
#endif

#if (0x045 == 0x0)
  // character: 'e'
  {0x65, &HellenicaRus8px_0x65},
#else
  // character: 'e' == 'E'
  {0x65, &HellenicaRus8px_0x45},
#endif

#if (0x046 == 0x0)
  // character: 'f'
  {0x66, &HellenicaRus8px_0x66},
#else
  // character: 'f' == 'F'
  {0x66, &HellenicaRus8px_0x46},
#endif

#if (0x047 == 0x0)
  // character: 'g'
  {0x67, &HellenicaRus8px_0x67},
#else
  // character: 'g' == 'G'
  {0x67, &HellenicaRus8px_0x47},
#endif

#if (0x048 == 0x0)
  // character: 'h'
  {0x68, &HellenicaRus8px_0x68},
#else
  // character: 'h' == 'H'
  {0x68, &HellenicaRus8px_0x48},
#endif

#if (0x049 == 0x0)
  // character: 'i'
  {0x69, &HellenicaRus8px_0x69},
#else
  // character: 'i' == 'I'
  {0x69, &HellenicaRus8px_0x49},
#endif

#if (0x04a == 0x0)
  // character: 'j'
  {0x6a, &HellenicaRus8px_0x6a},
#else
  // character: 'j' == 'J'
  {0x6a, &HellenicaRus8px_0x4a},
#endif

#if (0x04b == 0x0)
  // character: 'k'
  {0x6b, &HellenicaRus8px_0x6b},
#else
  // character: 'k' == 'K'
  {0x6b, &HellenicaRus8px_0x4b},
#endif

#if (0x04c == 0x0)
  // character: 'l'
  {0x6c, &HellenicaRus8px_0x6c},
#else
  // character: 'l' == 'L'
  {0x6c, &HellenicaRus8px_0x4c},
#endif

#if (0x04d == 0x0)
  // character: 'm'
  {0x6d, &HellenicaRus8px_0x6d},
#else
  // character: 'm' == 'M'
  {0x6d, &HellenicaRus8px_0x4d},
#endif

#if (0x04e == 0x0)
  // character: 'n'
  {0x6e, &HellenicaRus8px_0x6e},
#else
  // character: 'n' == 'N'
  {0x6e, &HellenicaRus8px_0x4e},
#endif

#if (0x030 == 0x0)
  // character: 'o'
  {0x6f, &HellenicaRus8px_0x6f},
#else
  // character: 'o' == '0'
  {0x6f, &HellenicaRus8px_0x30},
#endif

#if (0x050 == 0x0)
  // character: 'p'
  {0x70, &HellenicaRus8px_0x70},
#else
  // character: 'p' == 'P'
  {0x70, &HellenicaRus8px_0x50},
#endif

#if (0x051 == 0x0)
  // character: 'q'
  {0x71, &HellenicaRus8px_0x71},
#else
  // character: 'q' == 'Q'
  {0x71, &HellenicaRus8px_0x51},
#endif

#if (0x052 == 0x0)
  // character: 'r'
  {0x72, &HellenicaRus8px_0x72},
#else
  // character: 'r' == 'R'
  {0x72, &HellenicaRus8px_0x52},
#endif

#if (0x053 == 0x0)
  // character: 's'
  {0x73, &HellenicaRus8px_0x73},
#else
  // character: 's' == 'S'
  {0x73, &HellenicaRus8px_0x53},
#endif

#if (0x054 == 0x0)
  // character: 't'
  {0x74, &HellenicaRus8px_0x74},
#else
  // character: 't' == 'T'
  {0x74, &HellenicaRus8px_0x54},
#endif

#if (0x055 == 0x0)
  // character: 'u'
  {0x75, &HellenicaRus8px_0x75},
#else
  // character: 'u' == 'U'
  {0x75, &HellenicaRus8px_0x55},
#endif

#if (0x056 == 0x0)
  // character: 'v'
  {0x76, &HellenicaRus8px_0x76},
#else
  // character: 'v' == 'V'
  {0x76, &HellenicaRus8px_0x56},
#endif

#if (0x057 == 0x0)
  // character: 'w'
  {0x77, &HellenicaRus8px_0x77},
#else
  // character: 'w' == 'W'
  {0x77, &HellenicaRus8px_0x57},
#endif

#if (0x058 == 0x0)
  // character: 'x'
  {0x78, &HellenicaRus8px_0x78},
#else
  // character: 'x' == 'X'
  {0x78, &HellenicaRus8px_0x58},
#endif

#if (0x059 == 0x0)
  // character: 'y'
  {0x79, &HellenicaRus8px_0x79},
#else
  // character: 'y' == 'Y'
  {0x79, &HellenicaRus8px_0x59},
#endif

#if (0x05a == 0x0)
  // character: 'z'
  {0x7a, &HellenicaRus8px_0x7a},
#else
  // character: 'z' == 'Z'
  {0x7a, &HellenicaRus8px_0x5a},
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &HellenicaRus8px_0x7b},
#else
  // character: '{' == ''
  {0x7b, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '|'
  {0x7c, &HellenicaRus8px_0x7c},
#else
  // character: '|' == ''
  {0x7c, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '}'
  {0x7d, &HellenicaRus8px_0x7d},
#else
  // character: '}' == ''
  {0x7d, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &HellenicaRus8px_0x7e},
#else
  // character: '~' == ''
  {0x7e, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: '°'
  {0xc2b0, &HellenicaRus8px_0xc2b0},
#else
  // character: '°' == ''
  {0xc2b0, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'À'
  {0xc380, &HellenicaRus8px_0xc380},
#else
  // character: 'À' == ''
  {0xc380, &HellenicaRus8px_0x},
#endif

#if (0x0c380 == 0x0)
  // character: 'Á'
  {0xc381, &HellenicaRus8px_0xc381},
#else
  // character: 'Á' == 'À'
  {0xc381, &HellenicaRus8px_0xc380},
#endif

#if (0x0c380 == 0x0)
  // character: 'Â'
  {0xc382, &HellenicaRus8px_0xc382},
#else
  // character: 'Â' == 'À'
  {0xc382, &HellenicaRus8px_0xc380},
#endif

#if (0x0 == 0x0)
  // character: 'Ã'
  {0xc383, &HellenicaRus8px_0xc383},
#else
  // character: 'Ã' == ''
  {0xc383, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ä'
  {0xc384, &HellenicaRus8px_0xc384},
#else
  // character: 'Ä' == ''
  {0xc384, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Å'
  {0xc385, &HellenicaRus8px_0xc385},
#else
  // character: 'Å' == ''
  {0xc385, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Æ'
  {0xc386, &HellenicaRus8px_0xc386},
#else
  // character: 'Æ' == ''
  {0xc386, &HellenicaRus8px_0x},
#endif

#if (0x041 == 0x0)
  // character: 'А'
  {0xd090, &HellenicaRus8px_0xd090},
#else
  // character: 'А' == 'A'
  {0xd090, &HellenicaRus8px_0x41},
#endif

#if (0x0 == 0x0)
  // character: 'Б'
  {0xd091, &HellenicaRus8px_0xd091},
#else
  // character: 'Б' == ''
  {0xd091, &HellenicaRus8px_0x},
#endif

#if (0x042 == 0x0)
  // character: 'В'
  {0xd092, &HellenicaRus8px_0xd092},
#else
  // character: 'В' == 'B'
  {0xd092, &HellenicaRus8px_0x42},
#endif

#if (0x0 == 0x0)
  // character: 'Г'
  {0xd093, &HellenicaRus8px_0xd093},
#else
  // character: 'Г' == ''
  {0xd093, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Д'
  {0xd094, &HellenicaRus8px_0xd094},
#else
  // character: 'Д' == ''
  {0xd094, &HellenicaRus8px_0x},
#endif

#if (0x045 == 0x0)
  // character: 'Е'
  {0xd095, &HellenicaRus8px_0xd095},
#else
  // character: 'Е' == 'E'
  {0xd095, &HellenicaRus8px_0x45},
#endif

#if (0x0 == 0x0)
  // character: 'Ж'
  {0xd096, &HellenicaRus8px_0xd096},
#else
  // character: 'Ж' == ''
  {0xd096, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'З'
  {0xd097, &HellenicaRus8px_0xd097},
#else
  // character: 'З' == ''
  {0xd097, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'И'
  {0xd098, &HellenicaRus8px_0xd098},
#else
  // character: 'И' == ''
  {0xd098, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Й'
  {0xd099, &HellenicaRus8px_0xd099},
#else
  // character: 'Й' == ''
  {0xd099, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'К'
  {0xd09a, &HellenicaRus8px_0xd09a},
#else
  // character: 'К' == ''
  {0xd09a, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Л'
  {0xd09b, &HellenicaRus8px_0xd09b},
#else
  // character: 'Л' == ''
  {0xd09b, &HellenicaRus8px_0x},
#endif

#if (0x04d == 0x0)
  // character: 'М'
  {0xd09c, &HellenicaRus8px_0xd09c},
#else
  // character: 'М' == 'M'
  {0xd09c, &HellenicaRus8px_0x4d},
#endif

#if (0x048 == 0x0)
  // character: 'Н'
  {0xd09d, &HellenicaRus8px_0xd09d},
#else
  // character: 'Н' == 'H'
  {0xd09d, &HellenicaRus8px_0x48},
#endif

#if (0x030 == 0x0)
  // character: 'О'
  {0xd09e, &HellenicaRus8px_0xd09e},
#else
  // character: 'О' == '0'
  {0xd09e, &HellenicaRus8px_0x30},
#endif

#if (0x0 == 0x0)
  // character: 'П'
  {0xd09f, &HellenicaRus8px_0xd09f},
#else
  // character: 'П' == ''
  {0xd09f, &HellenicaRus8px_0x},
#endif

#if (0x050 == 0x0)
  // character: 'Р'
  {0xd0a0, &HellenicaRus8px_0xd0a0},
#else
  // character: 'Р' == 'P'
  {0xd0a0, &HellenicaRus8px_0x50},
#endif

#if (0x043 == 0x0)
  // character: 'С'
  {0xd0a1, &HellenicaRus8px_0xd0a1},
#else
  // character: 'С' == 'C'
  {0xd0a1, &HellenicaRus8px_0x43},
#endif

#if (0x054 == 0x0)
  // character: 'Т'
  {0xd0a2, &HellenicaRus8px_0xd0a2},
#else
  // character: 'Т' == 'T'
  {0xd0a2, &HellenicaRus8px_0x54},
#endif

#if (0x059 == 0x0)
  // character: 'У'
  {0xd0a3, &HellenicaRus8px_0xd0a3},
#else
  // character: 'У' == 'Y'
  {0xd0a3, &HellenicaRus8px_0x59},
#endif

#if (0x0 == 0x0)
  // character: 'Ф'
  {0xd0a4, &HellenicaRus8px_0xd0a4},
#else
  // character: 'Ф' == ''
  {0xd0a4, &HellenicaRus8px_0x},
#endif

#if (0x058 == 0x0)
  // character: 'Х'
  {0xd0a5, &HellenicaRus8px_0xd0a5},
#else
  // character: 'Х' == 'X'
  {0xd0a5, &HellenicaRus8px_0x58},
#endif

#if (0x0 == 0x0)
  // character: 'Ц'
  {0xd0a6, &HellenicaRus8px_0xd0a6},
#else
  // character: 'Ц' == ''
  {0xd0a6, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ч'
  {0xd0a7, &HellenicaRus8px_0xd0a7},
#else
  // character: 'Ч' == ''
  {0xd0a7, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ш'
  {0xd0a8, &HellenicaRus8px_0xd0a8},
#else
  // character: 'Ш' == ''
  {0xd0a8, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Щ'
  {0xd0a9, &HellenicaRus8px_0xd0a9},
#else
  // character: 'Щ' == ''
  {0xd0a9, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ъ'
  {0xd0aa, &HellenicaRus8px_0xd0aa},
#else
  // character: 'Ъ' == ''
  {0xd0aa, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ы'
  {0xd0ab, &HellenicaRus8px_0xd0ab},
#else
  // character: 'Ы' == ''
  {0xd0ab, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ь'
  {0xd0ac, &HellenicaRus8px_0xd0ac},
#else
  // character: 'Ь' == ''
  {0xd0ac, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Э'
  {0xd0ad, &HellenicaRus8px_0xd0ad},
#else
  // character: 'Э' == ''
  {0xd0ad, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Ю'
  {0xd0ae, &HellenicaRus8px_0xd0ae},
#else
  // character: 'Ю' == ''
  {0xd0ae, &HellenicaRus8px_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Я'
  {0xd0af, &HellenicaRus8px_0xd0af},
#else
  // character: 'Я' == ''
  {0xd0af, &HellenicaRus8px_0x},
#endif

#if (0x041 == 0x0)
  // character: 'а'
  {0xd0b0, &HellenicaRus8px_0xd0b0},
#else
  // character: 'а' == 'A'
  {0xd0b0, &HellenicaRus8px_0x41},
#endif

#if (0x0d091 == 0x0)
  // character: 'б'
  {0xd0b1, &HellenicaRus8px_0xd0b1},
#else
  // character: 'б' == 'Б'
  {0xd0b1, &HellenicaRus8px_0xd091},
#endif

#if (0x042 == 0x0)
  // character: 'в'
  {0xd0b2, &HellenicaRus8px_0xd0b2},
#else
  // character: 'в' == 'B'
  {0xd0b2, &HellenicaRus8px_0x42},
#endif

#if (0x0d093 == 0x0)
  // character: 'г'
  {0xd0b3, &HellenicaRus8px_0xd0b3},
#else
  // character: 'г' == 'Г'
  {0xd0b3, &HellenicaRus8px_0xd093},
#endif

#if (0x0d094 == 0x0)
  // character: 'д'
  {0xd0b4, &HellenicaRus8px_0xd0b4},
#else
  // character: 'д' == 'Д'
  {0xd0b4, &HellenicaRus8px_0xd094},
#endif

#if (0x045 == 0x0)
  // character: 'е'
  {0xd0b5, &HellenicaRus8px_0xd0b5},
#else
  // character: 'е' == 'E'
  {0xd0b5, &HellenicaRus8px_0x45},
#endif

#if (0x0d096 == 0x0)
  // character: 'ж'
  {0xd0b6, &HellenicaRus8px_0xd0b6},
#else
  // character: 'ж' == 'Ж'
  {0xd0b6, &HellenicaRus8px_0xd096},
#endif

#if (0x0d097 == 0x0)
  // character: 'з'
  {0xd0b7, &HellenicaRus8px_0xd0b7},
#else
  // character: 'з' == 'З'
  {0xd0b7, &HellenicaRus8px_0xd097},
#endif

#if (0x0d098 == 0x0)
  // character: 'и'
  {0xd0b8, &HellenicaRus8px_0xd0b8},
#else
  // character: 'и' == 'И'
  {0xd0b8, &HellenicaRus8px_0xd098},
#endif

#if (0x0d099 == 0x0)
  // character: 'й'
  {0xd0b9, &HellenicaRus8px_0xd0b9},
#else
  // character: 'й' == 'Й'
  {0xd0b9, &HellenicaRus8px_0xd099},
#endif

#if (0x0d09a == 0x0)
  // character: 'к'
  {0xd0ba, &HellenicaRus8px_0xd0ba},
#else
  // character: 'к' == 'К'
  {0xd0ba, &HellenicaRus8px_0xd09a},
#endif

#if (0x0d09b == 0x0)
  // character: 'л'
  {0xd0bb, &HellenicaRus8px_0xd0bb},
#else
  // character: 'л' == 'Л'
  {0xd0bb, &HellenicaRus8px_0xd09b},
#endif

#if (0x04d == 0x0)
  // character: 'м'
  {0xd0bc, &HellenicaRus8px_0xd0bc},
#else
  // character: 'м' == 'M'
  {0xd0bc, &HellenicaRus8px_0x4d},
#endif

#if (0x048 == 0x0)
  // character: 'н'
  {0xd0bd, &HellenicaRus8px_0xd0bd},
#else
  // character: 'н' == 'H'
  {0xd0bd, &HellenicaRus8px_0x48},
#endif

#if (0x030 == 0x0)
  // character: 'о'
  {0xd0be, &HellenicaRus8px_0xd0be},
#else
  // character: 'о' == '0'
  {0xd0be, &HellenicaRus8px_0x30},
#endif

#if (0x0d09f == 0x0)
  // character: 'п'
  {0xd0bf, &HellenicaRus8px_0xd0bf},
#else
  // character: 'п' == 'П'
  {0xd0bf, &HellenicaRus8px_0xd09f},
#endif

#if (0x050 == 0x0)
  // character: 'р'
  {0xd180, &HellenicaRus8px_0xd180},
#else
  // character: 'р' == 'P'
  {0xd180, &HellenicaRus8px_0x50},
#endif

#if (0x043 == 0x0)
  // character: 'с'
  {0xd181, &HellenicaRus8px_0xd181},
#else
  // character: 'с' == 'C'
  {0xd181, &HellenicaRus8px_0x43},
#endif

#if (0x054 == 0x0)
  // character: 'т'
  {0xd182, &HellenicaRus8px_0xd182},
#else
  // character: 'т' == 'T'
  {0xd182, &HellenicaRus8px_0x54},
#endif

#if (0x059 == 0x0)
  // character: 'у'
  {0xd183, &HellenicaRus8px_0xd183},
#else
  // character: 'у' == 'Y'
  {0xd183, &HellenicaRus8px_0x59},
#endif

#if (0x0d0a4 == 0x0)
  // character: 'ф'
  {0xd184, &HellenicaRus8px_0xd184},
#else
  // character: 'ф' == 'Ф'
  {0xd184, &HellenicaRus8px_0xd0a4},
#endif

#if (0x058 == 0x0)
  // character: 'х'
  {0xd185, &HellenicaRus8px_0xd185},
#else
  // character: 'х' == 'X'
  {0xd185, &HellenicaRus8px_0x58},
#endif

#if (0x0d0a6 == 0x0)
  // character: 'ц'
  {0xd186, &HellenicaRus8px_0xd186},
#else
  // character: 'ц' == 'Ц'
  {0xd186, &HellenicaRus8px_0xd0a6},
#endif

#if (0x0d0a7 == 0x0)
  // character: 'ч'
  {0xd187, &HellenicaRus8px_0xd187},
#else
  // character: 'ч' == 'Ч'
  {0xd187, &HellenicaRus8px_0xd0a7},
#endif

#if (0x0d0a8 == 0x0)
  // character: 'ш'
  {0xd188, &HellenicaRus8px_0xd188},
#else
  // character: 'ш' == 'Ш'
  {0xd188, &HellenicaRus8px_0xd0a8},
#endif

#if (0x0d0a9 == 0x0)
  // character: 'щ'
  {0xd189, &HellenicaRus8px_0xd189},
#else
  // character: 'щ' == 'Щ'
  {0xd189, &HellenicaRus8px_0xd0a9},
#endif

#if (0x0d0aa == 0x0)
  // character: 'ъ'
  {0xd18a, &HellenicaRus8px_0xd18a},
#else
  // character: 'ъ' == 'Ъ'
  {0xd18a, &HellenicaRus8px_0xd0aa},
#endif

#if (0x0d0ab == 0x0)
  // character: 'ы'
  {0xd18b, &HellenicaRus8px_0xd18b},
#else
  // character: 'ы' == 'Ы'
  {0xd18b, &HellenicaRus8px_0xd0ab},
#endif

#if (0x0d0ac == 0x0)
  // character: 'ь'
  {0xd18c, &HellenicaRus8px_0xd18c},
#else
  // character: 'ь' == 'Ь'
  {0xd18c, &HellenicaRus8px_0xd0ac},
#endif

#if (0x0d0ad == 0x0)
  // character: 'э'
  {0xd18d, &HellenicaRus8px_0xd18d},
#else
  // character: 'э' == 'Э'
  {0xd18d, &HellenicaRus8px_0xd0ad},
#endif

#if (0x0d0ae == 0x0)
  // character: 'ю'
  {0xd18e, &HellenicaRus8px_0xd18e},
#else
  // character: 'ю' == 'Ю'
  {0xd18e, &HellenicaRus8px_0xd0ae},
#endif

#if (0x0d0af == 0x0)
  // character: 'я'
  {0xd18f, &HellenicaRus8px_0xd18f}
#else
  // character: 'я' == 'Я'
  {0xd18f, &HellenicaRus8px_0xd0af}
#endif

};


const qymui::tFont HellenicaRus8px = { 167, HellenicaRus8px_array };
